"""ASTRO_BRICK with loose dreads: vectorizes the character like lego_squad, but every hanging lock becomes
its own part DREAD_1..n (root at the hairline) so it can swing; the face under the inner locks is rebuilt
(skin continues from the nearest visible skin, the face outline is drawn by the head's stroke).

Usage: python3 split_dreads.py <images_dir> [out.jsxinc]
"""
import json
import os
import sys

import cv2
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "lego_squad", "tools"))
import vectorize_squad as V  # noqa: E402

Y_ROOT = 395      # hairline where the locks leave the hair cap (source px)
Y_CUT = 412       # the head keeps its hair above this row; locks overlap it from Y_ROOT


def hook(ctx):
    rgb, fig, core, poly, yy, xx = ctx["rgb"], ctx["fig"], ctx["core"], ctx["poly"], ctx["yy"], ctx["xx"]
    head = poly["HEAD"]
    r, g, b = rgb[..., 0], rgb[..., 1], rgb[..., 2]
    blond = head & fig & (r > 125) & (g > 85) & (r - b > 55) & (yy > 430)
    blond = cv2.morphologyEx(blond.astype(np.uint8), cv2.MORPH_OPEN, V.disk(3)).astype(bool)
    n, lab, st, cen = cv2.connectedComponentsWithStats(blond.astype(np.uint8), connectivity=8)
    blobs = sorted([i for i in range(1, n) if st[i, 4] > 1500], key=lambda i: cen[i][0])
    cx = ctx["cx"]
    skin = head & fig & (np.abs(r - 118) < 30) & (np.abs(g - 59) < 22) & (np.abs(b - 31) < 18) & (yy > 400) & (np.abs(xx - cx) < 175)
    skin = cv2.morphologyEx(skin.astype(np.uint8), cv2.MORPH_OPEN, V.disk(2)).astype(bool)
    locks, meta = [], []
    for k, i in enumerate(blobs):
        m = lab == i
        ys = np.nonzero(m.any(1))[0]
        top, bot = ys.min(), ys.max()
        shape = np.zeros_like(m)
        top_rows = [np.nonzero(m[y])[0] for y in range(top, min(top + 12, bot))]
        x0 = int(np.median([c.min() for c in top_rows])); x1 = int(np.median([c.max() for c in top_rows]))
        for y in range(Y_ROOT, bot + 1):
            cols = np.nonzero(m[y])[0] if y >= top else np.arange(x0, x1 + 1)
            if len(cols):
                shape[y, cols.min():cols.max() + 1] = True
        shape = cv2.dilate(shape.astype(np.uint8), V.disk(V.HALF_LINE * 2 + 1)).astype(bool) & fig & (yy >= Y_ROOT)
        locks.append(shape)
        # the dark top of a lock melts into the hair: its outline starts where the blond does
        meta.append({"name": "DREAD_%d" % (k + 1), "root": [round(float((x0 + x1) / 2), 1), Y_ROOT], "len": int(bot + 12 - Y_ROOT),
                     "strokeFrom": int(top - 8)})
    # one pixel belongs to one lock (front-most = later in x order wins nothing; split overlaps by nearest blob centre)
    owner = np.full(head.shape, -1, int)
    dist = np.full(head.shape, 1e9)
    for k, i in enumerate(blobs):
        d = np.abs(xx - cen[i][0])
        sel = locks[k] & (d < dist)
        owner[sel] = k
        dist[sel] = d[sel]
    all_locks = owner >= 0
    # face shape: hull of the visible skin, widened to the middle of its outline
    pts = np.argwhere(skin & (yy < 700))[:, ::-1].astype(np.int32)
    hull = np.zeros(head.shape, np.uint8)
    cv2.fillPoly(hull, [cv2.convexHull(pts)], 1)
    face = cv2.dilate(hull, V.disk(V.HALF_LINE + 4)).astype(bool) & fig
    cut = all_locks & (yy >= Y_CUT)
    poly["HEAD"] = head & ~cut
    synth = {"HEAD": {"add": face & cut, "src": skin & ~all_locks, "mode": "plain"}}
    empty = np.zeros_like(head)
    for k, mt in enumerate(meta):
        poly[mt["name"]] = owner == k
        synth[mt["name"]] = {"add": empty, "src": empty, "keep_edge": True}   # no outline on top: dark print to the edge
    print("dreads:", [(m["name"], m["root"], m["len"]) for m in meta])
    return synth, {"dreads": meta}


def main(img_dir, out_path):
    cfg = dict(V.CHARS["ASTRO_BRICK"])
    data = V.vectorize("ASTRO_BRICK", cfg, img_dir, None, hook)
    # pivots of the locks: their roots
    for mt in data["dreads"]:
        data["pivots"][mt["name"]] = mt["root"]
    with open(out_path, "w") as f:
        f.write("// generated by tools/split_dreads.py - ASTRO_BRICK with loose dreads\n(" + json.dumps(data, separators=(",", ":")) + ")\n")
    print("->", out_path)


if __name__ == "__main__":
    a = sys.argv[1:]
    main(a[0], a[1] if len(a) > 1 else os.path.join(HERE, "..", "vectors", "ASTRO_BRICK_DREADS.jsxinc"))
